## environment.yml

name: gala-lipstick
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - pyg
  - networkx
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - scikit-learn
  - tqdm
  - tensorboard
  - pip
  - pip:
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - graphviz
    - pydot
